name: Main Branch Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 12,0 * * *'

permissions:
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build
      run: cd build && build.bat
      shell: cmd

    # - name: Run Microsoft Security DevOps
    #   uses: microsoft/security-devops-action@latest
    #   id: msdo

    # - name: Upload results to Security tab
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: ${{ steps.msdo.outputs.sarifFile }}

    - name: Upload artifact SirCab.CORE
      uses: actions/upload-artifact@v4
      with:
        name: SirCab.CORE
        path: out/SirCab.CORE

    - name: Upload artifact SirCab.CLI
      uses: actions/upload-artifact@v4
      with:
        name: SirCab.CLI
        path: out/SirCab.CLI

    - name: Upload artifact SirCab.CLI_fat
      uses: actions/upload-artifact@v4
      with:
        name: SirCab.CLI_fat
        path: out/SirCab.CLI_fat

    - name: Upload artifact SirCab.UI
      uses: actions/upload-artifact@v4
      with:
        name: SirCab.UI
        path: out/SirCab.UI

    - name: Upload artifact SirCab.UI_fat
      uses: actions/upload-artifact@v4
      with:
        name: SirCab.UI_fat
        path: out/SirCab.UI_fat